spring:
  application.name: ecommerce-management
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console.enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: grainandflavor@gmail.com
    password: 'zicy wrdd dfij dmmz'
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

logging.level.root: INFO